jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: alienfast/ci-node:5.0.18
    steps:
      - checkout
      - add_ssh_keys
      - restore_cache:
          key: yarn-all-branches
      - run: ncu -a
      - run: yarn install
      - run: yarn run releaseStart
      - run: yarn test:unit
      - save_cache:
          key: yarn-all-branches-{{ epoch }}
          paths:
            - ~/.cache/yarn/v1
            - .eslintcache
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ];
              then \
                 yarn run releaseFinish && npm run release
            fi
          name: Finish release and publish to npm
    working_directory: ~/i18next-loader
version: 2
